
skinparam backgroundColor #FFFFFF
skinparam noteBackgroundColor #e6e6fa
skinparam noteBorderColor #808080

skinparam  activity {
  ArrowColor #000000
  BackgroundColor #f0f8ff
  BorderColor #778899
}

skinparam  sequence {
  ArrowColor #000000
  BackgroundColor #f0f8ff
  BorderColor #778899
  LifeLineBorderColor #808080
  LifeLineBackgroundColor #f0f8ff
  ParticipantBorderColor #808080
  ParticipantBackgroundColor #f0f8ff
  ActorBackgroundColor #f0f8ff
  ActorBorderColor #4682b4
}

skinparam  class {
  BackgroundColor #f0f8ff
  BorderColor #696969
  ArrowColor #808080
  ArrowFontColor #ff7f50
  ArrowFontStyle bold
  ArrowFontSize 14
}


skinparam  state {
  BackgroundColor #f0f8ff
  BorderColor #778899
}

skinparam  usecase {
  BackgroundColor #f0f8ff
  BorderColor #778899
}

