@startuml

!include ./lib/color.inc

left to right direction

actor ユーザ

rectangle GomoCa {
  ユーザ -- (ゲームを実行する)
  ユーザ -- (戦略を登録する)
  ユーザ -- (盤面を作成する)
  ユーザ -- (特定の盤面をファイルを読込/保存する)
}

@enduml
